##
##   88""Yb     88""Yb     88     8b    d8     88   88     .dP"Y8
##   88__dP     88__dP     88     88b  d88     88   88     `Ybo."
##   88"""      88"Yb      88     88YbdP88     Y8   8P     o.`Y8b
##   88         88  Yb     88     88 YY 88     `YbodP'     8bodP'
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## @author Latvian PHP programmer Kristaps Drivnieks (Primus)
## @link https://Github.com/PrimusLV/FactionsPE
##
name: FactionsPE
author: "Kristaps Drivnieks aka. Primus"
api: [ 2.0.0 ]
main: factions\Main
version: 0.0.1#dev_b0
softdepend: [EconomyAPI, MassiveEconomy, GoldStd, PocketMoney, SimpleAuth, KillRate]

# Commands are registered with code

# Permissions are not set yet :/